### ISSUE TITLE
Improve "Bad layer" dialog and behaviour

### ISSUE THREAD

**Issue by haubourg** [qgis/qgis3_UIX_discussion#9]
The idea is to keep layers in qgis even if they have a worng datasource, and be able to update it afterwards. 
That way a user can still edit a project without deleting unhandled layers

**Comment by SrNetoChan** [comment]
I believe this could be an option in the Dialog, something like a "keep bad layers". But for that, we would probably need to implement a way of having "ghost" layers, because this layers should not be visible or used in any other widgets.

Another idea would be to, once the user fix a one of the layers, QGIS try to find and fix similar (in the same path layers).

**Comment by DelazJ** [comment]
Implemented in qgis/QGIS#9620 and many others
